[package]
name = "v2ray-rs-tray"
version.workspace = true
edition.workspace = true

[dependencies]
v2ray-rs-core = { path = "../core" }
v2ray-rs-process = { path = "../process" }
ksni = "0.3"
notify-rust = "4"
resvg.workspace = true
tokio.workspace = true
log.workspace = true
